Added Project
Applib-OpenHarmony/MaterialTextFields pull request #3
Opened 2022-06-23 08:49 UTC by neeraj-patidar

2022-06-24 05:07 UTC, samuel-abhishek requested changes
Please check and handle the review comments

2022-06-24 05:07 UTC, samuel-abhishek commented on entry/package-lock.json
> +  "name": "entry",
Delete the generated files.

2022-06-24 05:07 UTC, samuel-abhishek commented on entry/src/main/ets/MainAbility/pages/filled_sample.ets
> +//      onChanged: () => {
Remove the commented code. If this code is required, then add a different use case within the sample app. (Applies to all commented code in the sample app)

2022-06-24 05:07 UTC, samuel-abhishek commented on README.md
> +### Features
Add a gif showing the functionality of both outlined and filled material text fields.

2022-06-29 11:23 UTC, archanaatr commented on MaterialTextField/package.json
> +  "name": "MaterialTextField",
try to change to material-textfield

2022-06-29 12:24 UTC, archanaatr commented on entry/package.json
> +    "@ohos/MaterialTextField": "file:../MaterialTextField"
define as @ohos/materialtextfield

2022-06-29 12:25 UTC, archanaatr reviewed
pls chk the comments.

2022-06-30 05:09 UTC, archanaatr approved these changes
ok

2022-06-30 05:09 UTC, merged